name:                kasti

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- vector
- containers
- filepath
- directory
- time

- mtl
- transformers
- random
- aeson
- lens
- lens-aeson


library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -frefinement-level-hole-fits=1
  dependencies:
  - scotty
  - warp
  - http-types
  - feed
  - wreq
  - postgresql-simple
  - elm-bridge
  - servant-elm
  - parallel
  - async
  - process
  - lifted-async
  - unliftio
  - stm
  - resource-pool
  - aeson
  - servant
  - wai
  - servant-server
  - transformers
  - containers

executables:
  kasti-server:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kasti
    - unix
    - optparse-applicative
  elm-gen:
    main:                Main.hs
    source-dirs:         elm-gen
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kasti
    - optparse-applicative
    - elm-bridge
    - servant-elm
    - servant

tests:
  kasti-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - kasti
