resolver: nightly-2018-06-09

packages:
- '.'
# Dependency packages to be pulled from upstream that are not in the resolver
# (e.g., acme-missiles-0.3)
extra-deps: []


# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages
extra-package-dbs: []

image:
  containers:
    - base: mattiast/kasti-run:0.0.4
      name: kasti-backend
      # Optionally add a directory to a path inside the docker image.
      add:
        ../static/: /root/static/
