version: 2
jobs:
  build:
    docker:
      - image: nixorg/nix:circleci
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: nix_store1
      - run:
          name: Set up nix environment
          command: |
              nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
              nix-channel --update
              nix-env -iA docker -f '<nixpkgs>'
              nix-env -iA awscli -f '<nixpkgs>'
      - run:
          name: Build app image
          command: |
              nix-build -A image
              docker load -i result
      - run:
          name: Login to AWS ECR
          command: eval $(aws ecr get-login --no-include-email)
      - run:
          name: Push app image to ECR
          command: |
              docker tag kasti-backend:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/kasti-backend:0.1.$CIRCLE_BUILD_NUM
              docker                     push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/kasti-backend:0.1.$CIRCLE_BUILD_NUM
      - run:
          name: Build scripts image
          command: |
              nix-build -A scriptImage
              docker load -i result
      - run:
          name: Push script image to ECR
          command: |
              docker tag kasti-scripts:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/kasti-scripts:0.1.$CIRCLE_BUILD_NUM
              docker                     push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/kasti-scripts:0.1.$CIRCLE_BUILD_NUM
      - save_cache:
          paths:
            - /nix
          key: nix_store1-{{ epoch }}

# Required environment variables:
# - AWS_ACCOUNT_ID
# - AWS_ACCESS_KEY_ID
# - AWS_SECRET_ACCESS_KEY
# - AWS_DEFAULT_REGION
