version: 2
jobs:
  build:
    docker:
      - image: nixorg/nix:circleci
    steps:
      - checkout
      - setup_remote_docker
          version: 19.03.12
      - restore_cache:
          key: nix_store1
      - run:
          name: Set the right Nix channel, install utilities
          command: |
              nix-channel --add https://nixos.org/channels/nixos-20.03 nixpkgs
              nix-channel --update

              nix-env -iA docker -f '<nixpkgs>'
              nix-env -iA google-cloud-sdk -f '<nixpkgs>'
      - run:
          name: Build app image
          command: |
              nix-build -A image
              docker load -i result
      - run:
          name: Login to GCR
          command: |
              echo $GOOGLE_AUTH > $HOME/gcp-key.json
              gcloud auth activate-service-account --key-file $HOME/gcp-key.json
              gcloud auth configure-docker
      - run:
          name: Push app image to GCR
          command: |
              docker tag kasti-backend:latest $GOOGLE_GCR_HOST/$GOOGLE_PROJECT_ID/kasti-backend:0.1.$CIRCLE_BUILD_NUM
              docker push                     $GOOGLE_GCR_HOST/$GOOGLE_PROJECT_ID/kasti-backend:0.1.$CIRCLE_BUILD_NUM
      - run:
          name: Build scripts image
          command: |
              nix-build -A scriptImage
              docker load -i result
      - run:
          name: Push script image to GCR
          command: |
              docker tag kasti-scripts:latest $GOOGLE_GCR_HOST/$GOOGLE_PROJECT_ID/kasti-scripts:0.1.$CIRCLE_BUILD_NUM
              docker push                     $GOOGLE_GCR_HOST/$GOOGLE_PROJECT_ID/kasti-scripts:0.1.$CIRCLE_BUILD_NUM
      - save_cache:
          paths:
            - /nix
          key: nix_store1-{{ epoch }}

# Required environment variables:
# - GOOGLE_AUTH
# - GOOGLE_PROJECT_ID
# - GOOGLE_GCR_HOST
