version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-10.0
    steps:
      - checkout
      - restore_cache:
          key: stack_dir
      - run:
          name: Build stuff
          command: make release/kasti-server
      - save_cache:
          paths:
            - /root/.stack
          key: stack_dir-{{ epoch }}
      - store_artifacts:
          path: release/kasti-server
