version: 2
jobs:
  build:
    docker:
      - image: mattiast/kasti-build:0.0.6
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: stack_dir2
      - restore_cache:
          key: elm-stuff2
      - run:
          name: Build app image
          command: make
      - save_cache:
          paths:
            - /home/circleci/.stack
          key: stack_dir2-{{ epoch }}
      - save_cache:
          paths:
            - frontend/elm-stuff
          key: elm-stuff2-{{ epoch }}
      - run:
          name: Login to GCR
          command: |
              echo $GOOGLE_AUTH > $HOME/gcp-key.json
              gcloud auth activate-service-account --key-file $HOME/gcp-key.json
              gcloud --quiet config set project $GOOGLE_PROJECT_ID
              gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
              gcloud --quiet container clusters get-credentials $GOOGLE_CLUSTER_NAME
      - run:
          name: Push docker image to GCR
          command: |
              docker tag kasti-backend:latest gcr.io/$GOOGLE_PROJECT_ID/kasti-backend:0.0.$CIRCLE_BUILD_NUM
              gcloud docker --           push gcr.io/$GOOGLE_PROJECT_ID/kasti-backend:0.0.$CIRCLE_BUILD_NUM
      - run:
          name: Build scripts image
          command: make script-image
      - run:
          name: Push script image to GCR
          command: |
              docker tag kasti-scripts:latest gcr.io/$GOOGLE_PROJECT_ID/kasti-scripts:0.0.$CIRCLE_BUILD_NUM
              gcloud docker --           push gcr.io/$GOOGLE_PROJECT_ID/kasti-scripts:0.0.$CIRCLE_BUILD_NUM

          # Required environment variables:
          # - GOOGLE_AUTH
          # - GOOGLE_PROJECT_ID
          # - GOOGLE_CLUSTER_NAME
          # - GOOGLE_COMPUTE_ZONE
