version: 2
jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-10.0
    steps:
      - checkout
      - run:
          name: Greeting
          command: echo Hello, world.
      - run:
          name: Print the Current Time
          command: date
      - run:
          name: Build stuff
          command: make
