version: 2
jobs:
  build:
    docker:
      - image: mattiast/kasti-build:0.0.4
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: stack_dir2
      - restore_cache:
          key: elm-stuff2
      - run:
          name: Build stuff
          command: make
      - save_cache:
          paths:
            - /home/circleci/.stack
          key: stack_dir2-{{ epoch }}
      - save_cache:
          paths:
            - frontend/elm-stuff
          key: elm-stuff2-{{ epoch }}
      - store_artifacts:
          path: stuff.tar.gz
