version: 2
jobs:
  build:
    docker:
      - image: mattiast/kasti-build:0.1.3
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: nix_store0
      - run:
          name: Build app image
          command: |
              nix-build -A image
              docker load -i result
      - run:
          name: Login to GCR
          command: |
              echo $GOOGLE_AUTH > $HOME/gcp-key.json
              gcloud auth activate-service-account --key-file $HOME/gcp-key.json
              gcloud --quiet config set project $GOOGLE_PROJECT_ID
              gcloud --quiet config set compute/zone $GOOGLE_COMPUTE_ZONE
              gcloud --quiet container clusters get-credentials $GOOGLE_CLUSTER_NAME
      - run:
          name: Push app image to ECR
          command: |
              docker tag kasti-backend:latest gcr.io/$GOOGLE_PROJECT_ID/kasti-backend:0.0.$CIRCLE_BUILD_NUM
              gcloud docker --           push gcr.io/$GOOGLE_PROJECT_ID/kasti-backend:0.0.$CIRCLE_BUILD_NUM
      - run:
          name: Build scripts image
          command: |
              nix-build -A scriptImage
              docker load -i result
      - run:
          name: Push script image to ECR
          command: |
              docker tag kasti-scripts:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/kasti-scripts:0.1.$CIRCLE_BUILD_NUM
              docker                     push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/kasti-scripts:0.1.$CIRCLE_BUILD_NUM
      - save_cache:
          paths:
            - /nix
          key: nix_store0-{{ epoch }}

# Required environment variables:
# - GOOGLE_AUTH
# - GOOGLE_PROJECT_ID
# - GOOGLE_CLUSTER_NAME
# - GOOGLE_COMPUTE_ZONE
