version: 2
jobs:
  build:
    docker:
      - image: mattiast/kasti-build:latest
    steps:
      - checkout
      - restore_cache:
          key: stack_dir
      - restore_cache:
          key: elm-stuff
      - run:
          name: Build stuff
          command: make
      - save_cache:
          paths:
            - /root/.stack
          key: stack_dir-{{ epoch }}
      - save_cache:
          paths:
            - frontend/elm-stuff
          key: elm-stuff-{{ epoch }}
      - store_artifacts:
          path: release/kasti-server
