version: 2
jobs:
  build:
    docker:
      - image: mattiast/kasti-build:0.0.7
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          key: stack_dir3
      - restore_cache:
          key: elm-stuff4
      - run:
          name: Build app image
          command: make
      - run:
          name: Login to AWS ECR
          command: eval $(aws ecr get-login --no-include-email)
      - run:
          name: Push docker image to ECR
          command: |
              docker tag kasti-backend:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/kasti-backend:0.1.$CIRCLE_BUILD_NUM
              docker                     push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/kasti-backend:0.1.$CIRCLE_BUILD_NUM
      - save_cache:
          paths:
            - /home/circleci/.stack
          key: stack_dir3-{{ epoch }}
      - save_cache:
          paths:
            - frontend/elm-stuff
            - /home/circleci/.elm
          key: elm-stuff4-{{ epoch }}
      - run:
          name: Build scripts image
          command: make script-image
      - run:
          name: Push script image to ECR
          command: |
              docker tag kasti-scripts:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/kasti-scripts:0.1.$CIRCLE_BUILD_NUM
              docker                     push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/kasti-scripts:0.1.$CIRCLE_BUILD_NUM

          # Required environment variables:
          # - AWS_ACCOUNT_ID
          # - AWS_ACCESS_KEY_ID
          # - AWS_SECRET_ACCESS_KEY
          # - AWS_DEFAULT_REGION
