- hosts: webservers
  remote_user: root
  tasks:
  - name: Update apt
    when: ansible_os_family == "Debian"
    apt: update_cache=yes

  - name: install stuff
    when: ansible_os_family == "Debian"
    apt:
      name: "{{item}}"
      state: latest
    with_items:
      - libgmp10
      - tar
      - cron
      - libpq5
      - python3-pip
      - qt5-default
      - libqt5webkit5-dev
      - build-essential
      - xvfb

  - name: install python stuff
    pip:
      name: "{{item}}"
    with_items:
      - lxml
      - dryscrape
      - PyRSS2Gen
      - boto3
      - psycopg2

  - name: copy and extract tarball
    unarchive:
      src: ../stuff.tar.gz
      dest: /root
    notify: restart kasti

  - name: crontab
    cron:
      name: "update thf rss file"
      minute: "0"
      hour: "15,16,19"
      job: "python3 release/scripts/update_rss.py thf release/kasti-config.json"

  - name: crontab
    cron:
      name: "update korp rss file"
      minute: "0"
      hour: "10,11,12"
      job: "python3 release/scripts/update_rss.py korp release/kasti-config.json"

  - name: copy systemd service file to server
    copy:
      src: kasti.service
      dest: /etc/systemd/system
      owner: root
      group: root
      mode: 0644

  - name: start service
    systemd:
      daemon_reload: yes
      name: kasti.service
      state: started

  handlers:
  - name: restart kasti
    systemd:
      daemon_reload: yes
      name: kasti.service
      state: restarted
