FROM ubuntu:16.04

RUN apt update && apt install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    iptables \
    libpq-dev \
    lxc \
    nodejs-legacy \
    npm \
    python-pip \
    sudo

RUN curl -sSL https://get.docker.com/ | sh
RUN curl -sSL https://get.haskellstack.org/ | sh
RUN npm install -g elm@0.18
RUN pip install awscli
RUN adduser circleci

USER circleci
WORKDIR /home/circleci

RUN stack setup --resolver lts-10.0
RUN echo 1 + 1 | stack ghci
