FROM nixos/nix

RUN nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
RUN nix-channel --update

RUN nix-env -iA docker -f '<nixpkgs>'
RUN nix-env -iA git -f '<nixpkgs>'
RUN nix-env -iA awscli -f '<nixpkgs>'
RUN nix-env -iA cacert -f '<nixpkgs>'
